CarSpendings/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from cars.views import IndexView
from accounts.views import registration_view, login_view, logout_view, AccountLoginView

from rest_framework.authtoken import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("register/", registration_view, name="register"),
    # path("login/", login_view, name="login"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("cars/", include("cars.urls")),
    # Rest framework urls
    path("api-data/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-token-auth/", views.obtain_auth_token, name="api-token-auth"),
]

api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register("cars", views.CarViewSet, basename="cars")
router.register("fillups", views.FillupViewSet, basename="fillups")

urlpatterns = [
    path("", include(router.urls)),
    path("profile/", views.AccountRetrieveView.as_view(), name="profile"),
]

cars/urls.py
from django.urls import path, include
from .views import (
    CarsListView,
    CarDetailView,
    CarDeleteView,
    CarUpdateView,
)

app_name = "cars"

urlpatterns = [
    path("", CarsListView.as_view(), name="list"),
    path("<int:car_id>/", CarDetailView.as_view(), name="car_details"),
    path("add_car/", CarsListView.as_view(), name="add_car"),
    path("update_car/<int:car_id>/", CarUpdateView.as_view(), name="update_car"),
    path("delete_car/<int:car_id>/", CarDeleteView.as_view(), name="delete_car"),
    # Fillups
    path("<int:car_id>/fillups/", include("fillups.urls")),
]

cars/models.py
from django.conf import settings
from django.db import models
from accounts.models import Account


class Car(models.Model):
    brand = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    year = models.PositiveSmallIntegerField(blank=True, null=True)
    mileage = models.PositiveSmallIntegerField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.brand} {self.model}"


class CarUnits(models.Model):
    DISTANCE_UNITS_CHOICE = {
        ("kilometers", "kilometers"),
        ("miles", "miles"),
    }
    FUEL_UNITS_CHOICE = {
        ("liters", "liters"),
        ("gallons", "gallons"),
    }

    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    distance_unit = models.CharField(max_length=64, choices=DISTANCE_UNITS_CHOICE)
    fuel_unit = models.CharField(max_length=64, choices=FUEL_UNITS_CHOICE)

    def __str__(self):
        return f"{self.fuel_economy_unit}"

    @property
    def fuel_economy_unit(self):
        if (
            self.DISTANCE_UNITS_CHOICE == "kilometers"
            and self.FUEL_UNITS_CHOICE == "liters"
        ):
            return f"l/100km"
        elif (
            self.DISTANCE_UNITS_CHOICE == "kilometers"
            and self.FUEL_UNITS_CHOICE == "gallons"
        ):
            return f"km/gal"
        elif (
            self.DISTANCE_UNITS_CHOICE == "miles" and self.FUEL_UNITS_CHOICE == "liters"
        ):
            return f"l/100mi"
        elif (
            self.DISTANCE_UNITS_CHOICE == "miles"
            and self.FUEL_UNITS_CHOICE == "gallons"
        ):
            return f"MPG"
        else:
            return None

cars/forms.py
from django import forms
from cars.models import Car


class CarModelForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ["brand", "model", "year", "mileage"]

cars/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    View,
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.views.generic.edit import FormMixin

from accounts.models import Account
from cars.models import Car
from cars.forms import CarModelForm
from fillups.models import Fillup


class IndexView(View):
    def get(self, request, *args, **kwargs):
        template = "cars/pages/index.html"
        return render(request, template)


class CarsListView(LoginRequiredMixin, FormMixin, ListView):
    template_name = "cars/pages/car_list.html"
    form_class = CarModelForm
    success_url = reverse_lazy("cars:list")
    context_object_name = "cars"

    def get_queryset(self):
        return Car.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        if form.is_valid():
            form.save(commit=False)
            user = self.request.user
            form.instance.user = Account.objects.get(id=user.id)
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class CarDetailView(LoginRequiredMixin, DetailView):
    model = Car
    template_name = "cars/pages/car_details.html"
    context_object_name = "car"
    pk_url_kwarg = "car_id"

    def get_object(self, queryset=None):
        return Car.objects.get(id=self.kwargs["car_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = Car.objects.get(id=self.kwargs["car_id"])
        try:
            fillups = Fillup.objects.filter(car=self.get_object()).latest("id")
        except Fillup.DoesNotExist:
            fillups = None
        context["car"] = car
        context["fillups"] = fillups
        return context


class CarUpdateView(UpdateView):
    template_name = "cars/pages/car_update.html"
    fields = ["brand", "model", "year", "mileage"]
    success_url = reverse_lazy("cars:list")

    def get_queryset(self):
        car_id = self.kwargs.get("car_id")
        return Car.objects.filter(id=car_id)

    def get_object(self, queryset=None):
        return Car.objects.get(id=self.kwargs["car_id"])

    def get_context_data(self, **kwargs):
        form = CarModelForm(instance=self.get_object())
        context = {
            "form": form,
        }
        return super().get_context_data(**context)


class CarDeleteView(DeleteView):
    model = Car
    pk_url_kwarg = "car_id"
    success_url = reverse_lazy("cars:list")

cars/templates/cars/pages/car_details.html
{% extends 'cars/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container pt-5">
		<div class="row">
			<div class="col">
			<h4>Overview of {{ car }}</h4>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<div class="card text-center">
					<div class="card-header">
						Fillups
					</div>
					<div class="card-body">
{#						<h5 class="card-title">Recent</h5>#}
						<p class="card-text">
							Last fillup:
							{% if fillups %}
								{{ fillups.date|date:"D d M Y" }}
							{% else %}
								-- No fillups yet --
							{% endif %}
						</p>
						<a href="{% url 'cars:fillups:list' car.id %}"
						   class="btn btn-primary btn-sm">Check fillups</a>
					</div>
					<div class="card-footer text-muted">
						Last update: 2 days ago
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card text-center">
					<div class="card-header">
						Repairs
					</div>
					<div class="card-body">
{#						<h5 class="card-title">Recent</h5>#}
						<p class="card-text">Last repair: -- No repair yet --</p>
						<a href="#" class="btn btn-primary btn-sm">Check repairs</a>
					</div>
					<div class="card-footer text-muted">
						Last update: 2 days ago
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

cars/templates/cars/pages/car_list.html
{% extends 'cars/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="container pt-5">
		<div class="row">
			<div class="col d-flex flex-column align-items-center">
				<div class="row w-100 justify-content-md-center">
					{% for car in cars %}
						<div class="col col-md-3">
							<div class="card m-2">
								<div class="card-body">
									<h5 class="card-title text-center">
										<a href="{% url 'cars:car_details' car.id %}">{{ car }}</a>
									</h5>
									<p class="card-text text-center">
										<small>Model year: {{ car.year }}</small>
									</p>
									<p class="card-text text-center">
										<small>Mileage: {{ car.mileage }} km</small>
									</p>
									<div class="d-flex justify-content-between">
										<form method="POST" action="{% url "cars:update_car" car.id %}">
											{% csrf_token %}
												<input type="submit" value="Edit" class="btn
												btn-primary btn-sm">
										</form>
										<form method="POST" action="{% url "cars:delete_car" car.id %}">
											{% csrf_token %}
											<input type="submit" value="Delete" class="btn
											btn-primary btn-sm">
										</form>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
				<div class="pt-3">
					<h4>Add new car:</h4>
					<form method="POST" action="{% url 'cars:add_car' %}">
						{% csrf_token %}
						{{ form|crispy }}
						<button type="submit" class="btn btn-primary w-100">Add</button>
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

cars/templates/cars/pages/car_update.html
{% extends 'cars/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="container pt-5">
		<div class="row">
			<div class="col d-flex flex-column justify-content-center align-items-center">
				<h4 class="d-inline-block py-4">Update {{ car }} details:</h4>
				<form action="{% url 'cars:update_car' car.id %}" method="POST"
				      style="display:
    inline">
					{% csrf_token %}
					{{ form|crispy }}
					<button type="submit" class="btn btn-primary">Update</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

cars/templates/cars/pages/index.html
{% extends 'cars/base.html' %}

{% block content %}
	<div class="container height-excl-navbar d-flex justify-content-center align-items-center">
		<div class="row d-flex justify-content-center align-items-center">
			<div class="col d-flex flex-column justify-content-center align-items-center">

				<h1>---------Car App-------------</h1>
				<h2>---------Welcome!!-------------</h2>
			</div>
		</div>
	</div>
{% endblock %}