CarSpendings/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from cars.views import IndexView
from accounts.views import registration_view, login_view, logout_view, AccountLoginView

from rest_framework.authtoken import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("register/", registration_view, name="register"),
    # path("login/", login_view, name="login"),
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("cars/", include("cars.urls")),
    # Rest framework urls
    path("api-data/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-token-auth/", views.obtain_auth_token, name="api-token-auth"),
]

api/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views


router = routers.DefaultRouter()
router.register("cars", views.CarViewSet, basename="cars")
router.register("fillups", views.FillupViewSet, basename="fillups")

urlpatterns = [
    path("", include(router.urls)),
    path("profile/", views.AccountRetrieveView.as_view(), name="profile"),
]

cars/urls.py
from django.urls import path, include
from .views import (
    CarsListView,
    CarDetailView,
    CarDeleteView,
    CarUpdateView,
)

app_name = "cars"

urlpatterns = [
    path("", CarsListView.as_view(), name="list"),
    path("<int:car_id>/", CarDetailView.as_view(), name="car_details"),
    path("add_car/", CarsListView.as_view(), name="add_car"),
    path("update_car/<int:car_id>/", CarUpdateView.as_view(), name="update_car"),
    path("delete_car/<int:car_id>/", CarDeleteView.as_view(), name="delete_car"),
    # Fillups
    path("<int:car_id>/fillups/", include("fillups.urls")),
]

fillups/urls.py
from django.urls import path
from .views import (
    FillupListView,
    FillupUpdateView,
    FillupDeleteView,
)

app_name = "fillups"

urlpatterns = [
    path("", FillupListView.as_view(), name="list"),
    path("add_fillup/", FillupListView.as_view(), name="add_fillup"),
    path(
        "<int:fillup_id>/update_fillup/",
        FillupUpdateView.as_view(),
        name="update_fillup",
    ),
    path(
        "<int:fillup_id>/delete_fillup/",
        FillupDeleteView.as_view(),
        name="delete_fillup",
    ),
]

fillups/models.py
from django.db import models
from cars.models import Car
from .managers import FillupManager


class Fillup(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    odometer = models.PositiveSmallIntegerField()
    volume = models.FloatField()
    price_per_unit = models.FloatField()
    full_tank = models.BooleanField(default=False)
    date = models.DateTimeField(
        auto_now=False, auto_now_add=False, null=True, blank=True
    )
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = FillupManager()

    def __str__(self):
        return f"{self.date} - volume: {self.volume}"

    @property
    def total_price(self):
        return self.volume * self.price_per_unit

fillups/forms.py
from django import forms
from cars.models import Car

from .models import Fillup
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    Fieldset,
    ButtonHolder,
    Submit,
    Field,
    Div,
)
from crispy_forms.bootstrap import AppendedText


class FillupModelForm(forms.ModelForm):
    # hide 'car' field for Fillup add/update
    # add car_id to each fillup form
    def __init__(self, car_id, previous_fillup=None, update=False, *args, **kwargs):
        super(FillupModelForm, self).__init__(*args, **kwargs)
        self.car_id = car_id
        self.update = update
        self.previous_fillup = previous_fillup
        self.fields["car"].initial = Car.objects.get(id=car_id)
        self.fields["price_per_unit"].label = "Price"
        self.fields["full_tank"].label = "Full"
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset("Add new fillup"),
            Field("car", type="hidden"),
            Div(
                Div("date", css_class="form-group col-md-2 mb-0"),
                Div("volume", css_class="form-group col-md-2 mb-0"),
                Div("price_per_unit", css_class="form-group col-md-2 mb-0"),
                Div("odometer", css_class="form-group col-md-2 mb-0"),
                Div("full_tank", css_class="form-check col-auto mb-0"),
                ButtonHolder(
                    Submit("submit", "Add fillup", css_class="btn btn-primary")
                ),
                css_class="form-row align-items-center",
            ),
        )

    class Meta:
        model = Fillup
        fields = [
            "car",
            "odometer",
            "volume",
            "price_per_unit",
            "date",
            "full_tank",
        ]

    def clean_odometer(self):
        user_odometer = self.cleaned_data.get("odometer")

        if not self.update:
            qs = Fillup.objects.get_car_last_fillup(self.car_id)
            if qs:
                last_odometer = qs.odometer
                if user_odometer < last_odometer:
                    raise forms.ValidationError(
                        f"Odometer value cannot be lower than last input of {last_odometer}"
                    )
            else:
                if user_odometer < 0:
                    raise forms.ValidationError(
                        f"Odometer value cannot be lower than 0"
                    )
        else:
            previous_fillup = self.previous_fillup.odometer
            if previous_fillup:
                prev_odometer = previous_fillup
                if user_odometer < prev_odometer:
                    raise forms.ValidationError(
                        f"Odometer value cannot be lower than previous input of {prev_odometer}"
                    )
            else:
                if user_odometer < 0:
                    raise forms.ValidationError(
                        f"Odometer value cannot be lower than 0"
                    )

        return user_odometer

fillups/views.py
from django.contrib import messages
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView

from cars.models import Car
from fillups.models import Fillup
from fillups.forms import FillupModelForm


class FillupListView(ListView):
    model = Fillup
    template_name = "fillups/fillups_list.html"
    context_object_name = "fillups"

    def get_queryset(self):
        return Fillup.objects.filter(car_id=self.kwargs["car_id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car = Car.objects.get(id=self.kwargs["car_id"])
        form = FillupModelForm(car_id=self.kwargs["car_id"])
        context["car"] = car
        context["form"] = form
        return context

    def post(self, request, *args, **kwargs):
        car_id = self.kwargs["car_id"]
        form = FillupModelForm(car_id=car_id, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("cars:fillups:list", kwargs={"car_id": car_id}))


class FillupUpdateView(UpdateView):
    template_name = "fillups/fillup_update.html"
    fields = ["car", "odometer", "volume", "price_per_unit", "date", "full_tank"]
    success_url = reverse_lazy("cars:fillups:list")

    def get_queryset(self):
        fillup_id = self.kwargs.get("fillup_id")
        return Fillup.objects.filter(id=fillup_id)

    def get_object(self, queryset=None):
        return Fillup.objects.get(id=self.kwargs["fillup_id"])

    def get_context_data(self, **kwargs):
        fillup = self.get_object()
        previous_fillup = Fillup.objects.get_car_previous_fillup(
            fillup.car.id, fillup.id
        )
        form = FillupModelForm(
            instance=fillup,
            car_id=fillup.car.id,
            update=True,
            previous_fillup=previous_fillup,
        )
        context = {
            "form": form,
            "fillup": fillup,
            "car": fillup.car,
        }
        return super().get_context_data(**context)

    def post(self, request, *args, **kwargs):
        fillup = self.get_object()
        previous_fillup = Fillup.objects.get_car_previous_fillup(
            fillup.car.id, fillup.id
        )
        form = FillupModelForm(
            data=request.POST,
            instance=fillup,
            car_id=fillup.car.id,
            update=True,
            previous_fillup=previous_fillup,
        )
        if form.is_valid():
            form.save()
            return redirect(
                reverse_lazy("cars:fillups:list", kwargs={"car_id": fillup.car.id})
            )
        else:
            messages.error(
                self.request,
                "Fill up has not been updated. "
                "Odometer value cannot be lower than previous input",
            )
            return redirect(
                reverse_lazy("cars:fillups:list", kwargs={"car_id": fillup.car.id})
            )


class FillupDeleteView(DeleteView):
    model = Fillup
    pk_url_kwarg = "fillup_id"

    def get_success_url(self):
        car_id = self.kwargs["car_id"]
        return reverse_lazy("cars:fillups:list", kwargs={"car_id": car_id})

fillups/templates/fillups/fillup_update.html
{% extends 'Cars/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="container pt-5">
		<div class="row">
			<div class="col d-flex flex-column justify-content-center align-items-center">
				<h4 class="d-inline-block py-4">Update fillup details for {{ car }}</h4>
				<form action="{% url 'cars:fillups:update_fillup' car.id fillup.id %}"
				      method="POST" style="display: inline">
					{% csrf_token %}
					{{ form|crispy }}
					<input type="submit" value="Update" class="btn
										btn-primary btn-sm font-weight-bold">
				</form>

			</div>
		</div>
	</div>

{% endblock %}

fillups/templates/fillups/fillups_list.html
{% extends 'cars/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="container pt-5">
		<div class="row">
			<div class="col d-flex flex-column justify-content-center align-items-center">
				<h4 class="d-inline-block py-4">
					Fillups for {{ car }}, model year {{ car.year }} (id:
					{{ car.id }})
				</h4>

				{#			Message for fillup update#}
				{% if messages %}
					<div class="d-block justify-content-center align-items-center"
					     style="height: 30px">
						{% for message in messages %}
							{{ message }}
						{% endfor %}
					</div>
				{% endif %}
				<table class="table table-sm table-hover">
					<thead>
					<tr>
						<th scope="col">Date</th>
						<th scope="col">Volume</th>
						<th scope="col">Price</th>
						<th scope="col">Total</th>
						<th scope="col">Full</th>
						<th scope="col">Odometer</th>
						<th scope="col">Actions</th>
					</tr>
					</thead>

					<tbody>
					{% if fillups %}
						{% for fillup in fillups %}
							<tr>
								<td>{{ fillup.date|date:'d-M-Y' }}</td>
								<td>{{ fillup.volume }}</td>
								<td>{{ fillup.price_per_unit }}</td>
								<td>{{ fillup.total_price }}</td>
								<td>{{ fillup.full_tank|yesno:'Yes,No' }}</td>
								<td>{{ fillup.odometer }}</td>
								<td class="d-flex">
									<a href="{% url 'cars:fillups:update_fillup' car.id fillup.id %}"
									   class="mr-2">
										<span class="btn btn-primary btn-sm font-weight-bold">Edit</span>
									</a>
									<form method="POST" action="{% url 'cars:fillups:delete_fillup' car.id fillup.id %}">
										{% csrf_token %}
										<input type="submit" value="Delete" class="btn
										btn-primary btn-sm font-weight-bold">
									</form>
								</td>
							</tr>
						{% endfor %}
					{% else %}
						<tr>
							<td colspan="8" class="text-center"> No fillups yet</td>
						</tr>
					{% endif %}
					</tbody>
				</table>

				<form action="{% url 'cars:fillups:add_fillup' car.id %}" method="POST">
					{% csrf_token %}
					{% crispy form %}
				</form>
				<br>
				<a href="{% url 'cars:list' %}">
					<span class="badge badge-primary p-2">Back to cars</span>
				</a>
			</div>
		</div>
	</div>
{% endblock %}